FROM tiangolo/nginx-rtmp

COPY default.conf /etc/nginx/nginx.conf

RUN  ls /home/
RUN  mkdir -p /home/rg/Desktop/projects/stream_live/video_feed
# RUN  chmod 777 /home/rg/Desktop/projects/stream_live/video_feed
RUN  chmod 777 /home/rg/Desktop/projects/stream_live/video_feed
